# -*- coding: utf-8 -*-
"""Base de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Mb9acviNUYBMqnz_pw6-5-esv52YiIS

# Preselección de datos
"""

import pandas as pd

# Cargar el dataset con separador ;
df = pd.read_csv("DATASET_FINAL_FILTRADO.csv", sep=';')

# Mostrar las primeras filas
df.head()

# Ver cantidad de filas y columnas
print("Filas y columnas:", df.shape)

# Ver tipos de datos y nulos
df.info()

# Ver nombres de las columnas
df.columns

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.head(2)

# Ver nombres de las columnas
df.columns

df.rename(columns={'iruc': 'identifcador_ruc'}, inplace=True)

df.drop(columns=['actividad_economica'], inplace=True)

# Ver nombres de las columnas
df.columns

df.drop(columns=['mercaderiaprincipal'], inplace=True)

# Ver nombres de las columnas
df.columns

df.drop(columns={'actividadeconomica'}, inplace=True)

df.rename(columns={'capital_pagado': 'capital_invertido'}, inplace=True)
df.rename(columns={'margen_comercial': 'gastos_por_prestamos'}, inplace=True)
df.rename(columns={'num_mes_operativo': 'meses_operando'}, inplace=True)
df.rename(columns={'pasivo_corriente': 'deudas_corto_plazo'}, inplace=True)
df.rename(columns={'patrimonio_neto': 'patrimonio_empresa'}, inplace=True)
df.rename(columns={'resultado_de_explotacion': 'ganancia_operativa'}, inplace=True)
df.rename(columns={'total_pasivo_no_corriente': 'deudas_largo_plazo'}, inplace=True)
df.rename(columns={'totalempleados': 'numero_empleados'}, inplace=True)
df.rename(columns={'ventas_netas_de_mercaderías': 'ventas_netas'}, inplace=True)
df.rename(columns={'canal_dominante': 'canal_principal'}, inplace=True)
df.rename(columns={'nro_canales_usados': 'cantidad_canales_venta'}, inplace=True)
df.rename(columns={'usa_catalogo': 'vende_por_catalogo'}, inplace=True)
df.rename(columns={'usa_comisionistas': 'vende_con_comisionistas'}, inplace=True)
df.rename(columns={'usa_domicilio': 'vende_a_domicilio'}, inplace=True)
df.rename(columns={'usa_ecommerce': 'vende_en_linea'}, inplace=True)
df.rename(columns={'usa_maquinas': 'vende_en_maquinas_venta'}, inplace=True)
df.rename(columns={'usa_mostrador': 'vende_en_tienda'}, inplace=True)
df.rename(columns={'usa_ferias': 'vende_en_ferias'}, inplace=True)
df.rename(columns={'usa_otros': 'otros_medios_venta'}, inplace=True)
df.rename(columns={'usa_telefono': 'vende_por_telefono'}, inplace=True)

df.drop(columns=['inventarios','obligaciones_financieras_con_bancos1','obligaciones_financieras_con_bancos2','prestación_de_servicios','ventas_netas_de_productos_terminados,_subproductos,_desechos_y_desperdicios','ventas_catalogo', 'ventas_comisionistas',
       'ventas_domicilio', 'ventas_ecommerce', 'ventas_ferias',
       'ventas_maquinas', 'ventas_mostrador', 'ventas_otros',
       'ventas_telefono', 'ventas_total', 'ventas_total_canal13','identifcador_ruc','año'], inplace=True)

df.drop(columns=['nummeses'], inplace=True)

df.drop(columns=['ventas'], inplace=True)

df.drop(columns=['usa_total'], inplace=True)

df.drop(columns=['ciiu'], inplace=True)

df.drop(columns=['distrito'], inplace=True)

df.columns
df.shape
# Ver nombres de las columnas
df.columns

df.to_csv('DATASET_FINAL_LIMPIO.csv', sep=';', index=False)
df.to_excel('DATASET_FINAL_LIMPIO.xlsx', index=False)

"""# EDA

Variables Financieras
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar dataset
df = pd.read_csv('DATASET_FINAL_LIMPIO.csv', sep=';')

# Mostrar primeras filas
df.head()

binarias = [
    'vende_por_catalogo',
    'vende_con_comisionistas',
    'vende_a_domicilio',
    'vende_en_linea',
    'vende_en_ferias',
    'vende_en_maquinas_venta',
    'vende_en_tienda',
    'otros_medios_venta',
    'vende_por_telefono',
    'uso_de_software',
    'sobrevive_2años'
]
df[binarias] = df[binarias].astype(bool)

df.info()
print("\nValores nulos por columna:")
print(df.isna().sum())

df.describe().T

"""Tratamiento o ajuste de outliers"""

import numpy as np

# Seleccionamos las columnas numéricas relevantes (financieras)
cols_financieras = [
    'activo_corriente', 'capital_invertido', 'gastos_financieros',
    'gastos_por_prestamos', 'deudas_corto_plazo', 'patrimonio_empresa',
    'ganancia_operativa', 'total_activo', 'deudas_largo_plazo','total_pasivo_y_patrimonio',
    'ventas_netas'
]

# Calculamos IQR y mostramos posibles outliers por variable
for col in cols_financieras:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col}: {len(outliers)} outliers encontrados")

for col in cols_financieras:
    negativos = df[df[col] < 0]
    if len(negativos) > 0:
        print(f"⚠️ {col} tiene {len(negativos)} valores negativos")

for col in cols_financieras:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

df['gastos_por_prestamos'] = np.where(df['gastos_por_prestamos'] < 0, 0, df['gastos_por_prestamos'])

import seaborn as sns
import matplotlib.pyplot as plt

for c in cols_financieras:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[c])
    plt.title(f'Distribución ajustada: {c}')
    plt.show()

df[cols_financieras].describe().T

for col in cols_financieras:
    print(f"{col}: min={df[col].min()}, max={df[col].max()}")

df.sample(5)

"""Relación entre variables financieras"""

cols_financieras = [
    'activo_corriente',
    'capital_invertido',
    'gastos_financieros',
    'gastos_por_prestamos',
    'deudas_corto_plazo',
    'patrimonio_empresa',
    'ganancia_operativa',
    'total_activo',
    'deudas_largo_plazo',
    'total_pasivo_y_patrimonio',
    'ventas_netas',
    'sobrevive_2años'  # Incluimos la variable objetivo
]

corr = df[cols_financieras].corr()
print(corr.round(3))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Matriz de correlación - Variables financieras")
plt.show()

# Definir todas las variables financieras
cols_financieras = [
    'activo_corriente', 'capital_invertido', 'gastos_financieros',
    'gastos_por_prestamos', 'deudas_corto_plazo', 'patrimonio_empresa',
    'ganancia_operativa', 'total_activo', 'deudas_largo_plazo',
    'total_pasivo_y_patrimonio', 'ventas_netas'
]

# Comparar los promedios según supervivencia
df.groupby('sobrevive_2años')[cols_financieras].mean().round(2)

"""Relación entre variables cualitativas"""

# Limpiar espacios en todas las columnas tipo texto
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Para ver la frecuencia de categorías
print(df['canal_principal'].value_counts())
print(df['departamento'].value_counts())

# Comparar tasas de supervivencia por canal o departamento
pd.crosstab(df['canal_principal'], df['sobrevive_2años'], normalize='index') * 100

"""# Variables No Financieras"""

df.columns

df.info()

cols_no_financieras= [
    'canal_principal',
    'numero_empleados',
    'cantidad_canales_venta',
    'vende_por_catalogo',
    'vende_con_comisionistas',
    'vende_a_domicilio',
    'vende_en_linea',
    'vende_en_ferias',
    'vende_en_maquinas_venta',
    'vende_en_tienda',
    'otros_medios_venta',
    'vende_por_telefono',
    'uso_de_software'
    ]

df[cols_no_financieras]

df[cols_no_financieras].info()

"""Tratamiento de nulos (No Financieras)"""

df.isnull().sum().sort_values(ascending=False)[cols_no_financieras]

df[df['cantidad_canales_venta'].isna()][cols_no_financieras]

df.loc[20, 'cantidad_canales_venta'] = 2

df.isnull().sum().sort_values(ascending=False)[cols_no_financieras]

df['cantidad_canales_venta'] = df['cantidad_canales_venta'].astype(int)

df[cols_no_financieras].info()

df['canal_principal'].value_counts()

df['canal_principal'] = df['canal_principal'].replace({
    'ventas_catalogo': 'ventas_por_catalogo',
    'ventas_comisionistas': 'ventas_con_comisionistas',
    'ventas_telefono': 'ventas_por_telefono',
    'ventas_maquinas': 'ventas_en_maquinas_venta',
    'ventas_otros': 'ventas_otro_medio',
    'ventas_ferias': 'ventas_en_ferias'
})

df['canal_principal'].value_counts()

df['canal_principal'].value_counts(ascending=True).plot.barh();

df['numero_empleados'].plot(kind='hist', bins=10, edgecolor='black', figsize=(8,5))
plt.title('Distribución del número de empleados por empresa')
plt.xlabel('Número de empleados')
plt.ylabel('Cantidad de empresas')
plt.show()

df['uso_de_software'].value_counts()

df['uso_de_software'].value_counts(ascending=True).plot.barh();

df['canal_principal'] = df['canal_principal'].replace({
    'ventas_mostrador': 1,
    'ventas_domicilio': 2,
    'ventas_por_catalogo': 3,
    'ventas_con_comisionistas': 4,
    'ventas_por_telefono': 5,
    'ventas_ecommerce': 6,
    'ventas_en_maquinas_venta': 7,
    'ventas_en_ferias': 8,
    'ventas_otro_medio': 9
})

df['canal_principal'] = df['canal_principal'].astype(int)

df[cols_no_financieras].info()

pd.set_option('display.max_columns', None)   # 🔹 Muestra todas las columnas
pd.set_option('display.width', None)         # 🔹 Evita saltos de línea automáticos

df.head()

df.to_csv('DATASET_FINAL.csv', sep=';', index=False)
df.to_excel('DATASET_FINAL.xlsx', index=False)

